backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home
        name: home
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: src/pages/ministries/index.md
        label: Ministries
        name: ministries
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ministries"}
          - {label: "Path", name: "path", widget: "hidden", default: "/ministries"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: src/pages/directions/index.md
        label: Directions
        name: directions
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "directions"}
          - {label: "Path", name: "path", widget: "hidden", default: "/directions"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: src/pages/contact/index.md
        label: Contact
        name: contact
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
          - {label: "Path", name: "path", widget: "hidden", default: "/contact"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}